---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/25/2025 1:31 PM
---
--- Create zerg playable units
---
local ZergPlayableEntity = {}

local zergling = require('prototypes/entities/zergling')
local ultralisk = require('prototypes/entities/ultralisk')
local mutalisk = require('prototypes/entities/mutalisk')
local infested = require('prototypes/entities/infested')
local hydralisk = require('prototypes/entities/hydralisk')
local guardian = require('prototypes/entities/guardian')
local hatchery = require('prototypes/entities/hatchery')

function ZergPlayableEntity.zergling(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    zergling.make(prefix, hp_mp, damage_mp)
end

function ZergPlayableEntity.hydralisk(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    hydralisk.make(prefix, hp_mp, damage_mp)
end

function ZergPlayableEntity.mutalisk(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    mutalisk.make(prefix, hp_mp, damage_mp)
end

function ZergPlayableEntity.guardian(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    guardian.make(prefix, hp_mp, damage_mp)
end

function ZergPlayableEntity.infested(prefix, SDA, hp_mp, damage_mp)
    if type(SDA) ~= 'string' then
        error('SELF_DESTRUCT_ATTACK is not defined for zerg economy')
    end
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    infested.make(prefix, hp_mp, damage_mp, SDA)
end

function ZergPlayableEntity.ultralisk(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    ultralisk.make(prefix, hp_mp, damage_mp)
end

function ZergPlayableEntity.hatchery(prefix)
    hatchery.make(prefix)
end

function ZergPlayableEntity.init(prefix)
    data:extend({
        { 
            type = "recipe-category", 
            name = prefix.."--erm_controllable" 
        },
        {
            type = "item-subgroup",
            name = prefix.."--erm_controllable" ,
            group = "combat",
            order = prefix.."--erm_controllable"
        },
        {
            type = "ammo-category",
            name = prefix.."--erm_controllable",
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            subgroup = "ammo-category"
        },
    })
end

return ZergPlayableEntity