---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/22/2025 1:31 PM
---
--- Create egg item, tech and recipe
---
local FusionEconomy = require("__erm_libs__/prototypes/fusion_economy_helper")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")


local ZergLarva = {}

local function get_secondary_color(color)
    color = util.table.deepcopy(color)
    local limit = (240/255)
    local change_r = 60/255
    local change_g = 32/255
    if color.r + change_r < limit then
        color.r = color.r + change_r
    end
    if color.g + change_g < limit then
        color.g = color.g + change_g
    end
    return color
end

function ZergLarva.init()
    data.extend({
        {
            type = "item-subgroup",
            name = "erm-egg-processes",
            group = "intermediate-products",
            order = "m"
        },
    })
end

function ZergLarva.create_item(name, trigger_name, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    data.extend({
        {
            type = "item",
            name = name,
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/larva_egg.png",
            pictures = {
                {
                    layers = {
                        { size = 64, filename = "__erm_zerg_hd_assets__/graphics/entity/items/larva_egg/larva_egg_1.png", scale = 0.5 },
                        { size = 64, filename = "__erm_zerg_hd_assets__/graphics/entity/items/larva_egg/larva_egg_1_teamcolor.png", scale = 0.5, tint = color_tint, blend_mode = 'additive-soft' },
                    }
                }
            },
            fuel_category = "chemical",
            fuel_value = "10MJ",
            subgroup = "agriculture-products",
            order = "c[eggs]-a[zerg-larva]",
            inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
            pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
            drop_sound = space_age_item_sounds.agriculture_inventory_move,
            stack_size = 100,
            weight = 1 * kg,
            spoil_ticks = 0.5 * hour,
            --spoil_ticks = 10 * second,
            spoil_to_trigger_result = {
                items_per_trigger = 1,
                trigger = {
                    type = "direct",
                    action_delivery = {
                        type = "instant",
                        source_effects = {
                            {
                                type = "script",
                                effect_id = trigger_name,
                            },
                        }
                    }
                }
            }
        }
    })
end

function ZergLarva.create_larva_egg_duplication_recipe(egg_name, additional_ingredients, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    local ingredients = {
        {type = "item", name = egg_name, amount = 2}
    }
    
    if additional_ingredients then
        for _, ind in pairs(additional_ingredients) do
            table.insert(ingredients, ind)
        end            
    end

    data.extend({{
                     type = "recipe",
                     name = egg_name.."-clone",
                     icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/larva_egg.png",
                     category = "organic",
                     subgroup = "erm-egg-processes",
                     order = "c["..egg_name.."]-a[larva]",
                     hide_from_player_crafting = true,
                     auto_recycle = false,
                     preserve_products_in_machine_output = true,
                     energy_required = 30,
                     ingredients = ingredients,
                     results =
                     {
                         {type = "item", name = egg_name, amount = 3}
                     },
                     result_is_always_fresh = true,
                     allow_productivity = true,
                     allow_quality = false,
                     enabled = false,
                     crafting_machine_tint =
                     {
                         primary = color_tint,
                         secondary = get_secondary_color(color_tint),
                     },
                 }
    })
end


function ZergLarva.create_larva_egg_to_nutrients_recipe(egg_name, nutrients_amount, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    data.extend({
        {
            type = "recipe",
            name = egg_name.."-to-nutrients",
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/nutrient-from-larve-egg.png",
            category = "organic",
            subgroup = "erm-egg-processes",
            order = "c["..egg_name.."]-a[egg-nutrients]",
            hide_from_player_crafting = true,
            auto_recycle = false,
            enabled = false,
            energy_required = 2,
            ingredients = {{type = "item", name = egg_name, amount = 1}},
            results = {{type="item", name="nutrients", amount= nutrients_amount}},
            allow_productivity = true,
            allow_quality = false,
            crafting_machine_tint =
            {
                primary = color_tint,
                secondary = get_secondary_color(color_tint),
            },
        }
        
    })
end

function ZergLarva.create_larva_egg_to_biter_egg_recipe(egg_name, additional_ingredients, color_tint)
    color_tint = util.table.deepcopy(color_tint)
    color_tint.a = 1
    local ingredients = {
        {type = "item", name = egg_name, amount = 1}
    }

    if additional_ingredients then
        for _, ind in pairs(additional_ingredients) do
            table.insert(ingredients, ind)
        end
    end

    data.extend({
    {
        type = "recipe",
        name = egg_name.."-to-biter-egg",
        icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/biter-egg-from-larve-egg.png",
        category = "organic",
        subgroup = "erm-egg-processes",
        order = "c["..egg_name.."]-a[egg-nutrients]",
        hide_from_player_crafting = true,
        auto_recycle = false,
        enabled = false,
        energy_required = 2,
        ingredients = ingredients,
        results = {{type="item", name="biter-egg", amount=1}},
        allow_productivity = true,
        allow_quality = false,
        crafting_machine_tint =
        {
            primary = color_tint,
            secondary = get_secondary_color(color_tint),
        },
    }})
end


function ZergLarva.create_larva_egg_to_uranium238_recipe(egg_name)
    FusionEconomy.init()
    data.extend({
        {
            type = "recipe",
            name = egg_name.."-to-uranium",
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/uranium-from-larve-egg.png",
            category = "fusion-assembly",
            order = "c["..egg_name.."]-a[uranium-238]",
            hide_from_player_crafting = true,
            auto_recycle = false,
            enabled = false,
            energy_required = 20,
            ingredients = {
                {type="item", name= egg_name, amount=1},
                {type="item", name="uranium-238", amount=10, ignored_by_stats = 10, ignored_by_productivity = 10},
                {type="fluid", name="fusion-plasma", amount= 2}
            },
            results = {
                {type = "item", name = "uranium-238", amount = 11, ignored_by_stats = 10, ignored_by_productivity = 10},
                {type= "fluid", name="fluoroketone-hot", amount= 2, temperature = 180, ignored_by_stats = 2, ignored_by_productivity = 2}
            },
            allow_productivity = true,
            allow_quality = false,
        }})
end

function ZergLarva.create_tech(egg_name)
    data.extend({
        {
            type = "technology",
            name = egg_name.."-processing",
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/items/larva_egg.png",
            icon_size = 64,
            effects =
            {
                {
                    type = "unlock-recipe",
                    recipe = egg_name.."-clone"
                },
                {
                    type = "unlock-recipe",
                    recipe = egg_name.."-to-nutrients"
                },
                {
                    type = "unlock-recipe",
                    recipe = egg_name.."-to-biter-egg"
                },
                {
                    type = "unlock-recipe",
                    recipe = egg_name.."-to-uranium"
                }
            },
            research_trigger =
            {
                type = "build-entity",
                entity = "biochamber"
            }
        }
    })
end


return ZergLarva